<?php
return array (
  'name' => 
  array (
    'fieldid' => '181',
    'modelid' => '15',
    'siteid' => '1',
    'field' => 'name',
    'name' => '姓名',
    'tips' => '怎么称呼',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '20',
    'pattern' => '',
    'errortips' => '请输入您的姓名',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'50\',
  \'defaultvalue\' => \'怎么称呼\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '怎么称呼',
    'ispassword' => '0',
  ),
  'phone' => 
  array (
    'fieldid' => '182',
    'modelid' => '15',
    'siteid' => '1',
    'field' => 'phone',
    'name' => '电话',
    'tips' => '您的联系电话',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '20',
    'pattern' => '/^(1)[0-9]{10}$/',
    'errortips' => '请输入您的手机电话',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'30\',
  \'defaultvalue\' => \'您的联系电话\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '30',
    'defaultvalue' => '您的联系电话',
    'ispassword' => '0',
  ),
  'email' => 
  array (
    'fieldid' => '183',
    'modelid' => '15',
    'siteid' => '1',
    'field' => 'email',
    'name' => '电子邮箱',
    'tips' => '您的电子邮箱',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '/^[\\w\\-\\.]+@[\\w\\-\\.]+(\\.\\w+)+$/',
    'errortips' => '请输入您的电子邮箱',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'60\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '60',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'company' => 
  array (
    'fieldid' => '184',
    'modelid' => '15',
    'siteid' => '1',
    'field' => 'company',
    'name' => '公司名称',
    'tips' => '公司名称',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '请输入贵公司名称',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'60\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '60',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'content' => 
  array (
    'fieldid' => '186',
    'modelid' => '15',
    'siteid' => '1',
    'field' => 'content',
    'name' => '留言内容',
    'tips' => '留言内容',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '请输入您的留言内容',
    'formtype' => 'textarea',
    'setting' => 'array (
  \'width\' => \'100%\',
  \'height\' => \'46\',
  \'defaultvalue\' => \'\',
  \'enablehtml\' => \'1\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'width' => '100%',
    'height' => '46',
    'defaultvalue' => '',
    'enablehtml' => '1',
  ),
);
?>