<?php
return array (
  13 => 
  array (
    'id' => '13',
    'catid' => '25',
    'typeid' => '0',
    'title' => '首页_定制流程',
    'style' => '',
    'thumb' => 'http://jj-robot.com/uploadfile/2017/0111/20170111030009839.jpg',
    'keywords' => '',
    'description' => '',
    'posids' => '0',
    'url' => 'http://jj-robot.com/index.php?m=content&c=index&a=show&catid=10&id=43',
    'listorder' => '1',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => '谢惠云',
    'inputtime' => '1468305035',
    'updatetime' => '1468987239',
    'pcatid' => '0',
    'hitsid' => 'c-16-13',
    'views' => '14',
    'yesterdayviews' => '3',
    'dayviews' => '7',
    'weekviews' => '10',
    'monthviews' => '14',
  ),
  14 => 
  array (
    'id' => '14',
    'catid' => '25',
    'typeid' => '0',
    'title' => '联系我们',
    'style' => '',
    'thumb' => 'http://jj-robot.com/uploadfile/2016/0727/20160727095048417.jpg',
    'keywords' => '',
    'description' => '',
    'posids' => '0',
    'url' => '',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'jj-robot.com',
    'inputtime' => '1469584205',
    'updatetime' => '1469584334',
    'pcatid' => '21',
    'hitsid' => 'c-16-14',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  8 => 
  array (
    'id' => '8',
    'catid' => '25',
    'typeid' => '0',
    'title' => '人才招聘',
    'style' => '',
    'thumb' => 'http://jj-robot.com/uploadfile/2016/0712/20160712020613915.jpg',
    'keywords' => '',
    'description' => '',
    'posids' => '0',
    'url' => 'http://jj-robot.com/index.php?m=content&c=index&a=lists&catid=20',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'jj-robot.com',
    'inputtime' => '1447717007',
    'updatetime' => '1447717173',
    'pcatid' => '20',
    'hitsid' => 'c-16-8',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  1 => 
  array (
    'id' => '1',
    'catid' => '25',
    'typeid' => '0',
    'title' => '首页_baby',
    'style' => '',
    'thumb' => 'http://jj-robot.com/uploadfile/2017/0112/20170112100103744.jpg',
    'keywords' => '',
    'description' => '',
    'posids' => '0',
    'url' => 'http://jj-robot.com/index.php?m=content&c=index&a=lists&catid=11',
    'listorder' => '4',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'jj-robot.com',
    'inputtime' => '1434007802',
    'updatetime' => '1434008022',
    'pcatid' => '0',
    'hitsid' => 'c-16-1',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  7 => 
  array (
    'id' => '7',
    'catid' => '25',
    'typeid' => '0',
    'title' => '关于我们',
    'style' => '',
    'thumb' => 'http://jj-robot.com/uploadfile/2015/1130/20151130022250113.jpg',
    'keywords' => '',
    'description' => '',
    'posids' => '0',
    'url' => 'http://jj-robot.com/index.php?m=content&c=index&a=lists&catid=9',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'jj-robot.com',
    'inputtime' => '1447716961',
    'updatetime' => '1447716995',
    'pcatid' => '9',
    'hitsid' => 'c-16-7',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  6 => 
  array (
    'id' => '6',
    'catid' => '25',
    'typeid' => '0',
    'title' => '服务案例',
    'style' => '',
    'thumb' => 'http://jj-robot.com/uploadfile/2017/0111/20170111044210302.jpg',
    'keywords' => '',
    'description' => '',
    'posids' => '0',
    'url' => 'http://jj-robot.com/index.php?m=content&c=index&a=lists&catid=7',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'jj-robot.com',
    'inputtime' => '1447716931',
    'updatetime' => '1447716952',
    'pcatid' => '7',
    'hitsid' => 'c-16-6',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  5 => 
  array (
    'id' => '5',
    'catid' => '25',
    'typeid' => '0',
    'title' => '产品中心',
    'style' => '',
    'thumb' => 'http://jj-robot.com/uploadfile/2017/0111/20170111024552364.jpg',
    'keywords' => '',
    'description' => '',
    'posids' => '0',
    'url' => 'http://jj-robot.com/index.php?m=content&c=index&a=lists&catid=6',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'jj-robot.com',
    'inputtime' => '1447716791',
    'updatetime' => '1447716820',
    'pcatid' => '6',
    'hitsid' => 'c-16-5',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '25',
    'typeid' => '0',
    'title' => '首页_andy2',
    'style' => '',
    'thumb' => 'http://jj-robot.com/uploadfile/2017/0111/20170111030048734.jpg',
    'keywords' => '',
    'description' => '',
    'posids' => '0',
    'url' => 'http://jj-robot.com/index.php?m=content&c=index&a=lists&catid=7',
    'listorder' => '3',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'jj-robot.com',
    'inputtime' => '1434008951',
    'updatetime' => '1434008988',
    'pcatid' => '0',
    'hitsid' => 'c-16-3',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '25',
    'typeid' => '0',
    'title' => '首页_andy1.',
    'style' => '',
    'thumb' => 'http://jj-robot.com/uploadfile/2017/0111/20170111035104358.jpg',
    'keywords' => '',
    'description' => '',
    'posids' => '0',
    'url' => 'http://jj-robot.com/index.php?m=content&c=index&a=lists&catid=10',
    'listorder' => '2',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'jj-robot.com',
    'inputtime' => '1434008874',
    'updatetime' => '1434008926',
    'pcatid' => '0',
    'hitsid' => 'c-16-2',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  10 => 
  array (
    'id' => '10',
    'catid' => '25',
    'typeid' => '0',
    'title' => '首页_andy3',
    'style' => '',
    'thumb' => 'http://jj-robot.com/uploadfile/2017/0113/20170113025623543.jpg',
    'keywords' => '',
    'description' => '',
    'posids' => '0',
    'url' => 'http://jj-robot.com/index.php?m=content&c=index&a=lists&catid=7',
    'listorder' => '5',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => '谢惠云',
    'inputtime' => '1465784984',
    'updatetime' => '1465785044',
    'pcatid' => '0',
    'hitsid' => 'c-16-10',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>